"use strict";

const fs = require("fs");
const path = require("path");

const envFile = path.join(__dirname, "..", ".env");
if (fs.existsSync(envFile)) {
  fs.readFileSync(envFile, "utf8").split("\n").forEach((line) => {
    const clean = line.trim();
    if (!clean || clean.startsWith("#")) return;
    const eqAt = clean.indexOf("=");
    if (eqAt < 1) return;
    const key = clean.slice(0, eqAt).trim();
    const value = clean.slice(eqAt + 1).trim();
    if (key && !process.env[key]) process.env[key] = value;
  });
}

const { handler } = require("../netlify/functions/marblism-bridge");

const SECRET = process.env.WEBHOOK_SECRET || "";
const GOOD_HEADERS = { "content-type": "application/json", authorization: `Bearer ${SECRET}` };
const BAD_HEADERS = { "content-type": "application/json", authorization: "Bearer wrong-secret" };

const TESTS = [
  {
    name: "Standard canonical field names",
    expect: 200,
    headers: GOOD_HEADERS,
    payload: {
      title: `[TEST-1] Standard shape - ${ts()}`,
      body: testBody("Standard shape test"),
      excerpt: "Testing the standard canonical payload shape.",
      author: "Naphtali Bryant",
      category: "Technology",
      image: "/assets/uploads/test.jpg",
      tags: ["test", "standard", "automation"],
      draft: true,
      publishDate: "2026-04-08",
    },
  },
  {
    name: "Alternate field names",
    expect: 200,
    headers: GOOD_HEADERS,
    payload: {
      post_title: `[TEST-2] Alias shape - ${ts()}`,
      content: testBody("Alias shape test"),
      summary: "Testing alias field name mapping.",
      byline: "Naphtali Bryant",
      topic: "Marketing",
      cover_image: "/assets/uploads/cover.jpg",
      tag_list: ["test", "aliases"],
      is_draft: true,
      publish_date: "2026-04-08",
    },
  },
  {
    name: "Missing title",
    expect: 400,
    headers: GOOD_HEADERS,
    payload: {
      body: "This post has content but no title field.",
    },
  },
  {
    name: "Wrong webhook secret",
    expect: 401,
    headers: BAD_HEADERS,
    payload: {
      title: "Test post",
      body: "Test content for secret validation.",
    },
  },
];

(async () => {
  const results = { passed: 0, failed: 0 };

  for (const test of TESTS) {
    const event = {
      httpMethod: "POST",
      path: "/.netlify/functions/marblism-bridge",
      headers: test.headers,
      body: JSON.stringify(test.payload),
    };

    let result;
    try {
      result = await handler(event);
    } catch (err) {
      console.error(`Unexpected handler error for "${test.name}": ${err.message}`);
      results.failed += 1;
      continue;
    }

    const passed = result.statusCode === test.expect;
    if (passed) results.passed += 1;
    else results.failed += 1;

    const body = safeParseJson(result.body);
    console.log(`${passed ? "PASS" : "FAIL"} ${test.name}: HTTP ${result.statusCode} expected ${test.expect}`);
    if (body.error) console.log(`  error: ${body.error}`);
    if (body.slug) console.log(`  slug: ${body.slug}`);
  }

  console.log(`Passed: ${results.passed}`);
  console.log(`Failed: ${results.failed}`);
})();

function ts() {
  return new Date().toISOString().slice(0, 19).replace("T", " ");
}

function testBody(label) {
  return `## ${label}\n\nThis is an automated test post generated by test-bridge.js.\n\nDelete the committed test file after validating the bridge.`;
}

function safeParseJson(str) {
  try {
    return JSON.parse(str);
  } catch {
    return {};
  }
}
